Added Golang
BaseMax/gregorian_to_jalali pull request #8
Opened 2022-01-20 15:41 UTC by aminasadiam

2022-01-20 17:06 UTC, BaseMax commented
Hi Amin,
Welcome, honestly we reserved Go for Parham, but I aware he is a bit busy. So we can check your PR. Thanks.

---------

Hi Parham, Can you take a look and review it? @1995parham

2022-01-20 18:04 UTC, 1995parham commented on GregorianToJalali.go
> +type DateStruct struct {
I think here using `Date` is better than `DateStruct`.

2022-01-20 18:04 UTC, 1995parham commented on GregorianToJalali.go
> +	return fmt.Sprintf("%d/%d/%d", result.Year, result.Month, result.Day)
we can have it as `String` method on `Date` struct.

2022-01-21 08:49 UTC, aminasadiam commented on GregorianToJalali.go
> +type DateStruct struct {
hi Mr.Parham, I made this change.

2022-01-21 08:51 UTC, aminasadiam commented on GregorianToJalali.go
> +	return fmt.Sprintf("%d/%d/%d", result.Year, result.Month, result.Day)
sorry, i didn't get you🤔

2022-01-21 09:15 UTC, aminasadiam commented on GregorianToJalali.go
> +	return fmt.Sprintf("%d/%d/%d", result.Year, result.Month, result.Day)
I made this change to.

2022-01-21 11:37 UTC, BaseMax commented
Please add more unit tests if possible. (`assert.Equal`)

2022-01-21 16:24 UTC, aminasadiam commented
Done. I hope it's ok. @BaseMax

2022-01-21 16:26 UTC, BaseMax commented
> Done. I hope it's ok. @BaseMax 

Hi Amin, thank you.
It's okay in my side. Pargam will comment and merge it.

Let me know if you want to add other languages too

Best
M.

2022-01-21 16:32 UTC, aminasadiam commented
Glad to participate. I can also add typescript. But I think Mr. Erfan will do that.

2022-01-22 04:19 UTC, BaseMax requested changes
We convert the day and month digit to two number not one.
For example: "1" => "01"

But your commit:
```go
func (d Date) String() string {
	return fmt.Sprintf("%d/%d/%d", d.Year, d.Month, d.Day)
}
```

You can see this in other languages too:
- https://github.com/BaseMax/gregorian_to_jalali/blob/main/gregorian_to_jalali.c#L58
- https://github.com/BaseMax/gregorian_to_jalali/blob/main/gregorian_to_jalali.js#L50

2022-01-22 14:29 UTC, aminasadiam commented
hi @BaseMax , I made this change.

2022-01-22 18:37 UTC, BaseMax commented
Hi, I going merge it, but this has some problem which need to fix.

2022-01-22 18:37 UTC, merged

2022-01-22 18:39 UTC, BaseMax commented
Check the commit and my change:
https://github.com/BaseMax/gregorian_to_jalali/commit/aabb5b401b100adeaf4a6e3efa6efcdc64b25a64

You will see `String` is how much easy and I removed all of your ifs.

2022-01-22 18:41 UTC, BaseMax commented
By the way, the **test file** is not ready yet and need contribute.
if want to work on, its: https://github.com/BaseMax/gregorian_to_jalali/blob/main/GregorianToJalali.test.go#L9